"""Initial Migration

Revision ID: 963e2a49b38b
Revises: 4959120ae0f5
Create Date: 2022-05-10 18:27:45.754439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963e2a49b38b'
down_revision = '4959120ae0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('users', 'profile_pic_path',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'profile_pic_path',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
