"""update Migration

Revision ID: ecca59dba4cd
Revises: 0635131d16ed
Create Date: 2022-05-09 15:26:20.885397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecca59dba4cd'
down_revision = '0635131d16ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
